### ISSUE TITLE
[Bug] failed to produce message with rocketMQ producer

### ISSUE THREAD

**Issue by xiaozongyang** [streamnative/rop#28]
I deploy rop as a plugin in pulsar standalone server, and I produce messages by a rocketMQ producer. by command `sh bin/tools.sh org.apache.rocketmq.example.quickstart.Producer` and it got `No route info of this topic: TopicTest` error.

- Pulsar version: 2.8.0
- Rop version: 0.1.0
- RocketMQ Producer Version: 4.9.0

The stack trace of rocketMQ producer is 
```log
org.apache.rocketmq.client.exception.MQClientException: No route info of this topic: TopicTest
See http://rocketmq.apache.org/docs/faq/ for further details.
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:694)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1384)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1328)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:330)
        at org.apache.rocketmq.example.quickstart.Producer.main(Producer.java:67)
```
And there are error logs in pulsar server output, full log is 
```log
11:09:31.781 [AdminBrokerThread_11] WARN  org.streamnative.pulsar.handlers.rocketmq.inner.namesvr.NameserverProcessor - fetch topic address of topic[TBW102] error.
java.lang.ClassCastException: org.apache.pulsar.broker.loadbalance.NoopLoadManager cannot be cast to org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper
        at org.streamnative.pulsar.handlers.rocketmq.inner.namesvr.NameserverProcessor.getModularLoadManagerImpl(NameserverProcessor.java:328) ~[pulsar-protocol-handler-rocketmq-0.1.0.nar-unpacked/:?]
        at org.streamnative.pulsar.handlers.rocketmq.inner.namesvr.NameserverProcessor.getBrokerAddressByListenerName(NameserverProcessor.java:299) ~[pulsar-protocol-handler-rocketmq-0.1.0.nar-unpacked/:?]
        at org.streamnative.pulsar.handlers.rocketmq.inner.namesvr.NameserverProcessor.handleTopicMetadata(NameserverProcessor.java:195) [pulsar-protocol-handler-rocketmq-0.1.0.nar-unpacked/:?]
        at org.streamnative.pulsar.handlers.rocketmq.inner.namesvr.NameserverProcessor.processRequest(NameserverProcessor.java:110) [pulsar-protocol-handler-rocketmq-0.1.0.nar-unpacked/:?]
        at org.streamnative.pulsar.handlers.rocketmq.inner.NettyRemotingAbstract$1.run(NettyRemotingAbstract.java:205) [pulsar-protocol-handler-rocketmq-0.1.0.nar-unpacked/:?]
        at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:80) [rocketmq-remoting-4.6.1.jar:4.6.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

When I check the source code of rop, it shows that `NoopLoadManager implements LoadManager` and `LoadManager` is **not** sub-class of `ModularLoadManager`.

**Comment by xiaozongyang** [comment]
When I change rop to version `0.2.0-SNAPSHOT` which built with brach master (git revision `10828842612cff48dc59d3e8f8f2fdd2d96ddac8`). The puslar standalone server can't start and following errors are showing in log
```log
11:38:34.963 [BrokerControllerScheduledThread1] ERROR org.streamnative.pulsar.handlers.rocketmq.inner.RocketMQBrokerController - schedule persist consumerOffset error.
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/streamnative/pulsar/handlers/rocketmq/inner/producer/ClientGroupAndTopicName
        at org.streamnative.pulsar.handlers.rocketmq.inner.consumer.ConsumerOffsetManager.createOffsetTableSnapshot(ConsumerOffsetManager.java:462) ~[pulsar-protocol-handler-rocketmq-0.2.0-SNAPSHOT.nar-unpacked/:?]
        at org.streamnative.pulsar.handlers.rocketmq.inner.consumer.ConsumerOffsetManager.neededPersistentOffsetTable(ConsumerOffsetManager.java:472) ~[pulsar-protocol-handler-rocketmq-0.2.0-SNAPSHOT.nar-unpacked/:?]
        at org.streamnative.pulsar.handlers.rocketmq.inner.consumer.ConsumerOffsetManager.persist(ConsumerOffsetManager.java:412) ~[pulsar-protocol-handler-rocketmq-0.2.0-SNAPSHOT.nar-unpacked/:?]
        at org.streamnative.pulsar.handlers.rocketmq.inner.RocketMQBrokerController$2.run(RocketMQBrokerController.java:243) [pulsar-protocol-handler-rocketmq-0.2.0-SNAPSHOT.nar-unpacked/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_192]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_192]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NoClassDefFoundError: org/streamnative/pulsar/handlers/rocketmq/inner/producer/ClientGroupAndTopicName
        ... 11 more
Caused by: java.lang.ClassNotFoundException: org.streamnative.pulsar.handlers.rocketmq.inner.producer.ClientGroupAndTopicName
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_192]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192]
        ... 11 more
```

**Comment by xiaozongyang** [comment]
When I add `loadManagerClassName=org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl` to `standalone.conf`, this problem is solved.
